# This is an exaple file containing passwords and other secrets that we don't want to 
# package into the final application. More info at README.md
spring:
    datasource:
        password: linuxstore
